export type Category = string;

export type Course = { id: string; title: string; description: string; category: Category; image: string };
export const categories: Category[] = ["Manutención y Carretillas", "Elevación y Plataformas", "Grúas y Equipos de Elevación", "Maquinaria y Movimiento de Tierras", "Logística y Almacén", "Prevención de Riesgos Laborales", "Manipulación y Seguridad"];

export type LessonSection = { heading: string; text: string; bullets?: string[] };
export type Lesson = { title: string; intro: string; points: string[]; sections?: LessonSection[]; references?: string[] };
export type Module = { id: string; title: string; lesson: Lesson };

const M = (id: string, title: string, lesson: string, intro: string, points: string[]): Module => ({ id, title, lesson: { title: lesson, intro, points } });

const temarios: Record<string, Module[]> = {
  carretillero: [
    {
      id: "1",
      title: "Módulo 1: Conocimiento de la carretilla elevadora",
      lesson: {
        title: "La máquina, sus componentes y sus límites de utilización",
        intro: "Antes de conducir una carretilla elevadora, el operador debe conocer qué máquina tiene delante, para qué está diseñada y qué límites no puede superar. Una carretilla no es simplemente un vehículo con horquillas: es un equipo de trabajo en el que la posición de la carga, la altura de elevación, el centro de gravedad, el terreno y la forma de conducir modifican la estabilidad. Por eso, la primera parte de la formación consiste en aprender a identificar sus elementos y comprender para qué sirve cada uno.",
        points: ["1.1. ¿Qué es una carretilla elevadora?","1.2. Partes principales","1.3. Mandos y dispositivos de seguridad","1.4. Placa de características y capacidad","1.5. Frontal y retráctil"],
        sections: [
          { heading: "1.1. ¿Qué es una carretilla elevadora?", text: "Una carretilla elevadora automotora es un equipo móvil destinado a transportar y manipular cargas. En una carretilla frontal contrapesada, la carga queda situada delante del eje delantero y el contrapeso trasero ayuda a mantener el equilibrio. El conjunto está diseñado para trabajar dentro de unas condiciones concretas de carga, altura, alcance y terreno. El operador debe conocer esas condiciones antes de comenzar, porque una máquina aparentemente estable puede perder estabilidad si se utiliza fuera de sus límites.", bullets: ["La carretilla debe utilizarse únicamente para las operaciones previstas por el fabricante. La carga tiene que ser compatible con las horquillas o implementos utilizados y debe encontrarse preparada para ser manipulada. El manual del fabricante y la placa o diagrama de cargas son referencias fundamentales para conocer las limitaciones del equipo."] },
          { heading: "1.2. Partes principales", text: "En una carretilla frontal podemos distinguir el chasis, el contrapeso, las ruedas, el puesto de conducción, el mástil, el tablero portahorquillas, las horquillas y los sistemas de elevación e inclinación. También existen elementos destinados específicamente a la protección del operador, como el tejadillo o estructura superior de protección y el sistema de retención del asiento cuando el modelo lo incorpora.", bullets: ["El operador debe ser capaz de localizar cada elemento y reconocer si presenta un daño evidente. Una horquilla doblada, una cadena deteriorada, una fuga hidráulica, un neumático dañado o un dispositivo de seguridad fuera de servicio no deben considerarse pequeños detalles: pueden afectar directamente a la seguridad de la operación."] },
          { heading: "1.3. Mandos y dispositivos de seguridad", text: "Antes de iniciar la marcha hay que identificar los mandos de avance y retroceso, dirección, freno, acelerador y las funciones hidráulicas de elevación e inclinación. También deben conocerse la bocina, luces, alarmas, sistemas de retención y cualquier dispositivo específico instalado por el fabricante.", bullets: ["Los dispositivos de seguridad no deben puentearse, anularse ni modificarse. Si una alarma, un cinturón, un sistema de presencia del operador o cualquier otro dispositivo esencial no funciona correctamente, la incidencia debe comunicarse y el equipo debe quedar fuera de servicio cuando el defecto comprometa la seguridad."] },
          { heading: "1.4. Placa de características y capacidad", text: "La capacidad de una carretilla no debe interpretarse como una autorización para levantar cualquier carga que pese menos que una cifra determinada. La capacidad admisible depende de factores como el centro de carga, la altura de elevación y la configuración del equipo. Por eso el operador debe consultar la placa o diagrama de cargas correspondiente a la máquina y a la configuración que está utilizando.", bullets: ["Por ejemplo, una carga que puede ser admisible cerca del suelo puede dejar de serlo al elevarla mucho o al aumentar la distancia entre su centro de gravedad y el respaldo de la horquilla. También puede cambiar la capacidad cuando se instala un accesorio. Ante cualquier duda debe prevalecer la información del fabricante, no una estimación realizada a ojo."] },
          { heading: "1.5. Frontal y retráctil", text: "La carretilla frontal contrapesada y la retráctil no deben conducirse como si fueran la misma máquina. La frontal está pensada para numerosas operaciones de carga y descarga y dispone de contrapeso trasero. La retráctil está especialmente orientada al trabajo en almacenes y pasillos, y su sistema de mástil y desplazamiento de la carga modifica la forma de realizar las maniobras.", bullets: ["La formación debe adaptarse al tipo concreto de carretilla. Saber conducir una frontal no significa automáticamente estar preparado para utilizar una retráctil. Hay que conocer los mandos, capacidades, radio de giro, comportamiento del mástil y procedimiento de trabajo de cada equipo."] }
        ],
        references: ["INSST · NTP 713: Carretillas elevadoras automotoras (I): conocimientos básicos para la prevención de riesgos."]
      }
    },
    {
      id: "2",
      title: "Módulo 2: Riesgos y prevención",
      lesson: {
        title: "Atropellos, vuelcos, golpes, atrapamientos y caída de cargas",
        intro: "El accidente con una carretilla rara vez depende de un único factor. La máquina, la carga, el entorno y la conducta del operador interactúan constantemente. Una puerta con visibilidad reducida, un peatón que aparece en un cruce, una carga mal colocada o una velocidad excesiva pueden convertir una maniobra normal en una situación peligrosa. Este módulo enseña a reconocer esos escenarios antes de que se produzca el accidente.",
        points: ["2.1. Atropellos y golpes","2.2. Vuelco","2.3. Caída o desplazamiento de la carga","2.4. Atrapamientos","2.5. Evaluación antes de trabajar"],
        sections: [
          { heading: "2.1. Atropellos y golpes", text: "Una carretilla puede producir lesiones graves aunque circule a una velocidad aparentemente moderada. El peso de la máquina y la dificultad para detenerla inmediatamente hacen especialmente importante separar, cuando sea posible, las rutas de peatones y vehículos. El operador no debe confiar en que una persona haya visto la carretilla ni en que vaya a apartarse.", bullets: ["En cruces, puertas, esquinas y zonas con obstáculos hay que reducir la velocidad y asegurarse de que la trayectoria está libre. Si la visibilidad no permite controlar el recorrido, la maniobra debe detenerse o realizarse aplicando el procedimiento establecido en el centro de trabajo."] },
          { heading: "2.2. Vuelco", text: "El vuelco puede producirse cuando el centro de gravedad del conjunto sale de la zona de estabilidad. Factores como una carga elevada, un giro rápido, una pendiente, una superficie irregular o una carga desplazada pueden aumentar el riesgo. La velocidad debe ser siempre compatible con las condiciones del terreno y de la carga.", bullets: ["En una carretilla con puesto de conducción sentado, el sistema de retención debe utilizarse correctamente. Ante un vuelco no se debe intentar saltar de forma impulsiva: el comportamiento de protección debe seguir las instrucciones del fabricante y el procedimiento de seguridad aplicable al equipo."] },
          { heading: "2.3. Caída o desplazamiento de la carga", text: "Una carga puede caer si está mal paletizada, si las horquillas no entran correctamente, si el peso está desplazado o si se circula con movimientos bruscos. Antes de levantarla hay que comprobar que el soporte está en buen estado y que la carga puede ser recogida de forma estable.", bullets: ["Durante el transporte se debe mantener la carga en una posición baja y estable, evitando elevaciones innecesarias. No deben transportarse cargas sueltas, inestables o incompatibles con la capacidad del equipo. Las dimensiones también importan: una carga larga o voluminosa puede cambiar la visibilidad y el comportamiento de la carretilla."] },
          { heading: "2.4. Atrapamientos", text: "Los puntos de atrapamiento aparecen entre la carretilla y una estructura, entre partes móviles del mástil o entre la carga y una estantería. El operador debe mantener manos y pies dentro de la zona prevista para su puesto y nunca introducir el cuerpo en espacios peligrosos durante una maniobra.", bullets: ["Las personas que trabajan alrededor de la carretilla también deben permanecer fuera de las zonas de riesgo. No se debe permitir que alguien pase o permanezca debajo de las horquillas elevadas o entre la carretilla y una estructura cuando exista posibilidad de movimiento."] },
          { heading: "2.5. Evaluación antes de trabajar", text: "Antes de empezar una tarea hay que mirar el recorrido completo: suelo, pendientes, puertas, cruces, estanterías, vehículos, peatones, altura libre y destino de la carga. Después se debe comprobar que la carretilla y el implemento son adecuados para esa tarea.", bullets: ["La prevención no consiste solamente en llevar equipos de protección. Consiste en identificar el peligro, eliminarlo cuando sea posible y establecer una forma segura de realizar la operación. Si una condición peligrosa no puede controlarse, el operador debe detenerse y comunicarla."] }
        ],
        references: ["INSST · NTP 714: Carretillas elevadoras automotoras (II): principales peligros y medidas preventivas."]
      }
    },
    {
      id: "3",
      title: "Módulo 3: Estabilidad y manipulación de cargas",
      lesson: {
        title: "Centro de gravedad, recogida, transporte, elevación y depósito",
        intro: "La estabilidad es uno de los conceptos centrales de la conducción de una carretilla. El operador debe entender que levantar una carga, alejarla del respaldo, girar, acelerar o circular por una pendiente modifica las fuerzas que actúan sobre el conjunto. En este módulo se explica la secuencia de trabajo que permite mantener el control desde que se recoge una carga hasta que se deposita.",
        points: ["3.1. Centro de gravedad y equilibrio","3.2. Recogida de una carga","3.3. Transporte","3.4. Rampas y pendientes","3.5. Depósito y apilado"],
        sections: [
          { heading: "3.1. Centro de gravedad y equilibrio", text: "Toda carga tiene un centro de gravedad. Cuando la carga se coloca sobre las horquillas, la posición de ese centro respecto del eje de la carretilla influye en la estabilidad. Cuanto más alejada esté la carga de la máquina, mayor será el efecto que produce sobre el equilibrio. Por eso la carga debe colocarse correctamente y, cuando la operación lo permita, próxima al respaldo de las horquillas.", bullets: ["La capacidad indicada por el fabricante debe consultarse teniendo en cuenta el centro de carga. No basta con conocer el peso: una carga de dimensiones diferentes puede tener el centro de gravedad en una posición distinta y generar un esfuerzo mayor sobre la carretilla."] },
          { heading: "3.2. Recogida de una carga", text: "La recogida comienza antes de mover las horquillas. Primero se comprueba que el palet o soporte está en condiciones, que la carga está estable y que el acceso está despejado. Después se alinea la carretilla con la carga y se introducen las horquillas de forma uniforme y suficientemente profunda según el procedimiento y el tipo de carga.", bullets: ["Una vez recogida, la carga se eleva solo lo necesario para poder desplazarse con seguridad. Los movimientos de elevación e inclinación deben hacerse progresivamente. Una maniobra brusca puede desplazar la carga o alterar la estabilidad del conjunto."] },
          { heading: "3.3. Transporte", text: "Durante el transporte la carga debe mantenerse baja y estable, sin elevarla innecesariamente. El operador debe observar el recorrido y conservar suficiente espacio para frenar. Si la carga bloquea la visión hacia delante, se debe utilizar el procedimiento previsto, que puede incluir circulación marcha atrás con especial atención al sentido de desplazamiento.", bullets: ["La velocidad no debe fijarse como una cifra aislada: debe permitir controlar la máquina en las condiciones reales. En un pasillo estrecho, cerca de peatones o sobre una superficie irregular, la velocidad segura será menor que en una zona amplia y despejada."] },
          { heading: "3.4. Rampas y pendientes", text: "Una pendiente modifica la distribución de fuerzas y exige especial atención. La orientación de la carretilla y de la carga debe realizarse siguiendo las instrucciones del fabricante y las normas del centro de trabajo. No se deben realizar giros improvisados sobre pendientes ni transportar la carga de manera que se pierda el control.", bullets: ["Antes de entrar en una pendiente hay que valorar su inclinación, estado de la superficie y espacio disponible. Si la situación no permite realizar la maniobra de forma segura, debe buscarse un recorrido alternativo o detener la operación."] },
          { heading: "3.5. Depósito y apilado", text: "Para depositar una carga se debe colocar la carretilla frente al destino, detenerla y realizar la elevación necesaria de forma controlada. La aproximación a una estantería debe evitar golpes contra largueros, protecciones y otras cargas. Una vez situada la carga, se retiran las horquillas cuidadosamente y se comprueba que la mercancía ha quedado estable.", bullets: ["El almacenamiento no termina al soltar la carga. Hay que comprobar que no sobresale de forma peligrosa, que el palet está apoyado correctamente y que la ubicación admite su peso y dimensiones. Una estantería dañada o una carga inestable debe comunicarse y no utilizarse como si estuviera en condiciones normales."] }
        ],
        references: ["INSST · NTP 713 y NTP 715 · principios de estabilidad, capacidad y utilización segura."]
      }
    },
    {
      id: "4",
      title: "Módulo 4: Circulación y trabajo en almacén",
      lesson: {
        title: "Rutas, peatones, cruces, estanterías, carga y descarga de vehículos",
        intro: "Una parte importante del trabajo del carretillero se desarrolla en zonas donde conviven máquinas, peatones, mercancías y vehículos. Por eso la conducción debe integrarse en una organización de tráfico. El operador debe aprender a anticiparse a los riesgos y a utilizar las zonas de circulación de acuerdo con la señalización y los procedimientos del centro.",
        points: ["4.1. Planificación del recorrido","4.2. Cruces y puertas","4.3. Peatones","4.4. Carga y descarga de camiones","4.5. Estanterías y zonas de almacenamiento"],
        sections: [
          { heading: "4.1. Planificación del recorrido", text: "Antes de mover una carga hay que saber de dónde se recoge, por dónde se transporta y dónde se deposita. El recorrido debe permitir el paso de la carretilla y de la carga, disponer de altura libre suficiente y evitar obstáculos. También deben revisarse las condiciones del suelo y las zonas donde puedan aparecer peatones.", bullets: ["Planificar evita improvisaciones. Si durante el recorrido aparece un obstáculo, una persona o una condición diferente de la prevista, el operador debe reducir la velocidad o detenerse y reevaluar la situación."] },
          { heading: "4.2. Cruces y puertas", text: "Los cruces y puertas son puntos especialmente sensibles porque pueden ocultar a otras personas o vehículos. Antes de atravesarlos hay que reducir la velocidad y comprobar la visibilidad. Cuando el procedimiento del centro lo establezca pueden utilizarse señales acústicas, espejos, luces u otras medidas de control.", bullets: ["Nunca se debe entrar rápidamente en una zona que no puede verse. La prioridad es poder detener la carretilla antes de alcanzar a una persona u obstáculo que aparezca inesperadamente."] },
          { heading: "4.3. Peatones", text: "El peatón debe disponer, siempre que sea posible, de recorridos separados de las carretillas. Cuando exista convivencia, el operador debe mantener una distancia adecuada y no iniciar una maniobra si la persona se encuentra en una zona de peligro.", bullets: ["Una carretilla puede tener ángulos muertos importantes. Por eso el operador debe comprobar el entorno antes de girar, retroceder o entrar en un pasillo. Si una persona se aproxima a la zona de maniobra, se debe detener el equipo hasta recuperar una condición segura."] },
          { heading: "4.4. Carga y descarga de camiones", text: "Antes de entrar o trabajar sobre un vehículo hay que comprobar que está correctamente situado e inmovilizado y que las condiciones de acceso son adecuadas. También debe comprobarse la resistencia del suelo, el estado de la plataforma y cualquier diferencia de altura.", bullets: ["No se debe comenzar una carga o descarga confiando únicamente en que el conductor del camión ha accionado el freno. Deben aplicarse las medidas de inmovilización y seguridad establecidas por el centro de trabajo."] },
          { heading: "4.5. Estanterías y zonas de almacenamiento", text: "Las estanterías deben mantenerse en condiciones adecuadas y sus capacidades deben respetarse. Los golpes de las carretillas pueden deteriorar elementos estructurales, por lo que la aproximación debe realizarse a baja velocidad y con control preciso.", bullets: ["Las cargas deben colocarse de forma estable y dentro de la ubicación prevista. Si se detecta un larguero deformado, un protector dañado o una carga con riesgo de caída, la zona debe señalizarse o aislarse según el procedimiento y comunicarse la incidencia."] }
        ],
        references: ["INSST · NTP 715: mantenimiento y utilización de carretillas elevadoras."]
      }
    },
    {
      id: "5",
      title: "Módulo 5: Carretilla retráctil",
      lesson: {
        title: "Trabajo en pasillos y almacenamiento en altura",
        intro: "La carretilla retráctil está diseñada para operaciones de almacenamiento en las que el espacio es reducido y la elevación puede alcanzar alturas importantes. Su manejo requiere conocer el comportamiento específico del mástil y del conjunto de carga. En este módulo el alumno aprende a preparar una ubicación, entrar en un pasillo, recoger o depositar un palet y salir de la zona de almacenamiento de forma controlada.",
        points: ["5.1. Características de la retráctil","5.2. Entrada en el pasillo","5.3. Elevación en altura","5.4. Extracción de un palet","5.5. Maniobras y errores frecuentes"],
        sections: [
          { heading: "5.1. Características de la retráctil", text: "La retráctil dispone de una configuración diferente de la frontal y puede desplazar el mástil o el conjunto de carga para acercarlo o separarlo del cuerpo de la máquina. Esta característica facilita el trabajo en pasillos, pero exige que el operador conozca las posiciones correctas del mástil y las capacidades correspondientes.", bullets: ["El hecho de que una máquina sea compacta no significa que pueda maniobrarse sin planificación. El operador debe controlar el espacio lateral, la altura de la carga, las estanterías y la presencia de otras máquinas."] },
          { heading: "5.2. Entrada en el pasillo", text: "Antes de entrar en un pasillo se comprueba que está libre y que la carga puede circular sin tocar estructuras. La velocidad debe reducirse y la máquina debe mantenerse alineada. En pasillos estrechos, pequeños errores de trayectoria pueden provocar golpes contra estanterías o mercancías.", bullets: ["La maniobra debe detenerse si una persona entra en el pasillo o si la visibilidad no permite controlar el recorrido. No se debe compensar una falta de espacio con movimientos bruscos de dirección."] },
          { heading: "5.3. Elevación en altura", text: "Cuando la carga se eleva aumenta la importancia de respetar el diagrama de cargas y las condiciones de la máquina. El operador debe comprobar que la ubicación tiene capacidad suficiente y que la carga está correctamente apoyada.", bullets: ["La elevación se realiza de manera progresiva. No se debe utilizar la horquilla o la carga para golpear una ubicación ni corregir una posición mediante impactos. El objetivo es colocar el palet con precisión y sin transmitir esfuerzos innecesarios a la estantería."] },
          { heading: "5.4. Extracción de un palet", text: "Para retirar una carga se comprueba primero que la ubicación está libre de obstáculos y que el palet puede salir sin engancharse. Las horquillas se introducen de manera alineada y la carga se asegura antes de retirarla.", bullets: ["Una vez liberada, la carga se coloca en una posición segura para el desplazamiento. El operador debe asegurarse de que la trayectoria de salida está despejada antes de iniciar la marcha."] },
          { heading: "5.5. Maniobras y errores frecuentes", text: "Entre los errores más peligrosos están circular demasiado rápido, girar sin comprobar el entorno, elevar una carga que excede la capacidad para esa altura, golpear estanterías o continuar una maniobra cuando la visibilidad es insuficiente.", bullets: ["La retráctil exige precisión y anticipación. Una buena operación no es la que termina más deprisa, sino la que mantiene el control de máquina, carga y entorno durante todo el proceso."] }
        ],
        references: ["INSST · NTP 713, 714 y 715 · formación específica, estabilidad, riesgos y utilización segura."]
      }
    },
    {
      id: "6",
      title: "Módulo 6: Mantenimiento, emergencias y casos prácticos",
      lesson: {
        title: "Comprobación diaria, averías, estacionamiento y aplicación práctica",
        intro: "El último bloque reúne los conocimientos necesarios para convertir la teoría en una rutina de trabajo. El operador debe saber revisar la máquina, reconocer una anomalía, actuar ante una situación peligrosa y finalizar el trabajo dejando el equipo en condiciones seguras. También se incluyen casos prácticos para comprobar que el alumno sabe aplicar los principios estudiados y no solo memorizar definiciones.",
        points: ["6.1. Inspección antes de usar","6.2. Batería y repostaje","6.3. Estacionamiento","6.4. Qué hacer ante una avería o accidente","6.5. Caso práctico: una carga bloquea la visión","6.6. Caso práctico: una persona entra en el pasillo","6.7. Caso práctico: carga por encima de la capacidad","6.8. Preparación final para la evaluación"],
        sections: [
          { heading: "6.1. Inspección antes de usar", text: "La revisión previa debe adaptarse al modelo y a las instrucciones del fabricante. Entre los elementos que normalmente deben comprobarse se encuentran ruedas, frenos, dirección, horquillas, mástil, cadenas, sistemas hidráulicos, señalización, luces, bocina, cinturón y dispositivos de seguridad.", bullets: ["La inspección no consiste en mirar rápidamente la máquina. Hay que buscar daños visibles, fugas, piezas deformadas, desgaste anormal o cualquier comportamiento que pueda indicar una avería. Si el defecto afecta a la seguridad, el equipo no debe ponerse en servicio hasta que se resuelva según el procedimiento establecido."] },
          { heading: "6.2. Batería y repostaje", text: "Las operaciones relacionadas con baterías y combustibles presentan riesgos específicos. Deben realizarse únicamente en las zonas y condiciones previstas, siguiendo las instrucciones del fabricante y utilizando los EPI establecidos.", bullets: ["No se debe fumar ni introducir fuentes de ignición en zonas donde exista riesgo de incendio o explosión. Ante una fuga, calentamiento anormal, daño en un cable o cualquier condición peligrosa, se debe detener la operación y comunicar la incidencia."] },
          { heading: "6.3. Estacionamiento", text: "Al terminar, la carretilla debe quedar en una zona autorizada y sin bloquear salidas, pasillos de emergencia, extintores u otros equipos. Las horquillas o implementos deben quedar apoyados en una posición segura, se debe aplicar el freno y el equipo debe apagarse y asegurarse conforme a las instrucciones.", bullets: ["Si la máquina queda en una pendiente, deben aplicarse las medidas adicionales previstas para impedir que se desplace. Nunca debe abandonarse una carretilla con la carga elevada o en una posición que pueda crear un riesgo para otras personas."] },
          { heading: "6.4. Qué hacer ante una avería o accidente", text: "Si aparece una avería durante la operación, el primer objetivo es dejar de generar peligro. El operador debe detenerse en condiciones seguras, asegurar la máquina cuando sea posible y comunicar el defecto. No debe realizar reparaciones para las que no esté autorizado.", bullets: ["Ante una caída de carga, vuelco, incendio u otra emergencia se debe proteger la zona, avisar a las personas responsables y seguir el plan de emergencia. No se debe intentar recuperar una carga inestable ni acercarse innecesariamente al equipo accidentado."] },
          { heading: "6.5. Caso práctico: una carga bloquea la visión", text: "Imagina que debes transportar un palet cuya altura impide ver el recorrido delantero. La decisión correcta no es continuar mirando por los laterales mientras se mantiene la misma velocidad. Primero debes valorar si la carga puede colocarse de otra manera. Si no es posible, debes aplicar el procedimiento de circulación previsto, asegurándote de que el recorrido está libre y manteniendo una velocidad que permita detenerte.", bullets: ["La enseñanza del caso es que el operador debe adaptar la conducción a la visibilidad. La carga no puede obligar a circular a ciegas."] },
          { heading: "6.6. Caso práctico: una persona entra en el pasillo", text: "Si durante una maniobra de almacenamiento aparece un peatón, la operación debe detenerse. No se debe confiar en que la persona se aparte ni intentar terminar rápidamente la maniobra. Se debe mantener la carretilla inmovilizada hasta que la zona vuelva a estar libre y sea posible continuar con seguridad.", bullets: ["La prevención consiste en anticiparse y detener la maniobra antes de que exista contacto. Una carga bien colocada nunca justifica continuar si hay una persona dentro de la zona de peligro."] },
          { heading: "6.7. Caso práctico: carga por encima de la capacidad", text: "Si el peso de una carga supera la capacidad admisible de la configuración utilizada, no debe intentarse levantarla aunque la carretilla parezca tener potencia suficiente. La capacidad depende de las condiciones indicadas por el fabricante y no puede sustituirse por una impresión visual del operador.", bullets: ["La respuesta profesional es utilizar un equipo o procedimiento adecuado para esa carga y comunicar la necesidad si los medios disponibles no permiten realizar el trabajo con seguridad."] },
          { heading: "6.8. Preparación final para la evaluación", text: "Para superar la evaluación el alumno debe comprender por qué se realizan las comprobaciones, cómo afecta la carga a la estabilidad, qué riesgos aparecen en la circulación y qué debe hacer ante una anomalía. El objetivo no es memorizar una lista aislada, sino saber tomar decisiones seguras.", bullets: ["La formación teórica debe complementarse con la formación práctica y con la autorización correspondiente para operar el equipo en un puesto de trabajo. El manual del fabricante y las instrucciones específicas del centro siempre deben respetarse."] }
        ],
        references: ["INSST · NTP 715: Carretillas elevadoras automotoras (III): mantenimiento y utilización.","INSST · NTP 714: principales peligros y medidas preventivas."]
      }
    }
  ],
  pemp: [
    M("1", "Módulo 1: Tipos de PEMP", "Plataformas de tijera y brazo", "Conoce los tipos de plataformas elevadoras y sus elementos principales.", ["PEMP de tijera, articulada y telescópica.", "Cesta, mástil/brazo, estabilizadores y controles.", "Capacidad de plataforma y limitaciones del fabricante.", "Manual, marcado y señalización del equipo."]),
    M("2", "Módulo 2: Trabajo seguro en altura", "Estabilidad, terreno y EPI", "La estabilidad y la protección contra caídas son esenciales durante el trabajo en altura.", ["Inspección del terreno y obstáculos.", "Estabilizadores y condiciones de viento.", "Arnés y punto de anclaje cuando proceda.", "Distancias de seguridad y riesgos eléctricos."]),
    M("3", "Módulo 3: Operación", "Mandos, desplazamiento y posicionamiento", "Practica mentalmente una secuencia segura desde la inspección hasta el posicionamiento.", ["Prueba de controles y revisión previa.", "Desplazamiento con plataforma según instrucciones del fabricante.", "Posicionamiento y trabajo cerca de estructuras.", "Carga máxima y prohibición de aumentar la altura con medios improvisados."]),
    M("4", "Módulo 4: Emergencias y mantenimiento", "Descenso de emergencia y conservación", "Conoce qué hacer ante un fallo y cómo mantener la máquina en condiciones seguras.", ["Sistemas de descenso y rescate.", "Comunicación de averías.", "Baterías, hidráulica, ruedas y elementos de seguridad.", "Retirada del servicio ante defectos graves."]),
  ],
  "puente-grua": [
    M("1", "Módulo 1: Puente grúa y polipasto", "Componentes y funcionamiento", "Identifica puente, carro, polipasto, gancho, mando y dispositivos de seguridad.", ["Puente, carro y mecanismos de elevación.", "Polipasto, cable/cadena y gancho.", "Limitador de carga y parada de emergencia.", "Capacidad y documentación del equipo."]),
    M("2", "Módulo 2: Eslingado y accesorios", "Preparación de la carga", "Una elevación segura depende de seleccionar y utilizar correctamente los accesorios.", ["Eslingas textiles, cadenas y accesorios.", "Inspección y retirada de eslingas dañadas.", "Centro de gravedad y ángulos de ramales.", "Protección de aristas y aseguramiento de la carga."]),
    M("3", "Módulo 3: Maniobras y señalización", "Izado y desplazamiento", "Realiza las maniobras de forma suave, controlada y coordinada con el señalista.", ["Señales y comunicación con el señalista.", "Elevación de prueba y desplazamiento controlado.", "Evitar balanceos y movimientos bruscos.", "Prohibición de pasar cargas sobre personas."]),
    M("4", "Módulo 4: Seguridad y mantenimiento", "Inspección y emergencias", "La prevención incluye revisar el equipo y detener la operación ante anomalías.", ["Revisión de ganchos, cables, frenos y mandos.", "Sobrecargas y riesgos de caída.", "Estacionamiento y desconexión.", "Actuación ante averías y emergencia."]),
  ],
  transpaleta: [
    M("1", "Módulo 1: Transpaleta manual y eléctrica", "Componentes y usos", "Conoce las diferencias entre transpaleta manual y eléctrica y sus usos habituales.", ["Horquillas, timón, ruedas y capacidad.", "Batería y mandos en equipos eléctricos.", "Tipos de palet y compatibilidad.", "Limitaciones de uso."]),
    M("2", "Módulo 2: Manipulación segura", "Carga y estabilidad", "Aprende a introducir correctamente las horquillas y transportar cargas estables.", ["Estado y distribución de la carga.", "Centro de gravedad y capacidad nominal.", "Cargas aseguradas y visibilidad.", "Prohibiciones y usos no previstos."]),
    M("3", "Módulo 3: Circulación", "Almacén, rampas y peatones", "La circulación debe adaptarse al entorno y priorizar la seguridad de las personas.", ["Velocidad y distancia de seguridad.", "Rampas y orientación de la carga.", "Cruces, puertas y zonas de peatones.", "Giros y visibilidad."]),
    M("4", "Módulo 4: Revisiones y batería", "Mantenimiento básico", "Revisa el equipo antes de usarlo y conoce las precauciones básicas de carga.", ["Ruedas, freno, timón y horquillas.", "Batería y cargador.", "Detección y comunicación de anomalías.", "Estacionamiento seguro."]),
  ],
  apilador: [
    M("1", "Módulo 1: Apilador eléctrico", "Tipos, mástil y mandos", "Conoce el apilador, su mástil, horquillas, plataforma y controles.", ["Apilador con conductor acompañante o plataforma.", "Mástil, horquillas y sistemas de elevación.", "Capacidad y diagrama de cargas.", "Mandos y dispositivos de seguridad."]),
    M("2", "Módulo 2: Estabilidad y carga", "Elevación y almacenamiento", "El apilado requiere controlar centro de gravedad, altura y capacidad.", ["Centro de gravedad y estabilidad.", "Recogida y depósito de palets.", "Altura de elevación y capacidad residual.", "Estanterías y estado del palet."]),
    M("3", "Módulo 3: Circulación", "Maniobras en almacén", "Circula de forma segura en pasillos, cruces y zonas compartidas.", ["Velocidad y visibilidad.", "Cruces y peatones.", "Rampas y pendientes.", "Marcha atrás y giros."]),
    M("4", "Módulo 4: Revisión y mantenimiento", "Inspección y estacionamiento", "La revisión diaria permite detectar defectos antes de iniciar el trabajo.", ["Frenos, dirección, ruedas y elevación.", "Batería y cargador.", "Averías y retirada del servicio.", "Estacionamiento y desconexión."]),
  ],
  "camion-pluma": [
    M("1", "Módulo 1: Grúa autocargable", "Componentes y capacidad", "Conoce la grúa sobre camión y la información necesaria para trabajar con seguridad.", ["Brazo, pluma, gancho y estabilizadores.", "Tabla o diagrama de cargas.", "Radio de trabajo y alcance.", "Documentación e inspección."]),
    M("2", "Módulo 2: Estabilización", "Terreno y estabilizadores", "La estabilidad depende del terreno, la configuración y el uso correcto de estabilizadores.", ["Nivelación del vehículo.", "Apoyos y resistencia del terreno.", "Configuración de estabilizadores.", "Zonas de exclusión y riesgos de vuelco."]),
    M("3", "Módulo 3: Izado", "Eslingado y maniobras", "Planifica la maniobra antes de elevar y evita sobrecargas y movimientos bruscos.", ["Peso, centro de gravedad y accesorios.", "Señalista y comunicación.", "Elevación y descenso progresivos.", "Prohibición de transportar personas con la carga."]),
    M("4", "Módulo 4: Seguridad", "Inspección y emergencias", "Una operación segura incluye revisar equipo, entorno y accesorios.", ["Ganchos, cables, hidráulica y mandos.", "Viento y condiciones meteorológicas.", "Averías y parada segura.", "Mantenimiento y comunicación de defectos."]),
  ],
  dumper: [
    M("1", "Módulo 1: Dúmper", "Tipos y componentes", "Identifica el equipo, sus controles y sus limitaciones de uso en obra.", ["Dúmper rígido y articulado.", "Caja, volquete, dirección y transmisión.", "Capacidad y distribución de carga.", "Mandos y señalización."]),
    M("2", "Módulo 2: Circulación en obra", "Pendientes y entorno", "La obra presenta riesgos cambiantes que requieren adaptar velocidad y recorrido.", ["Pendientes y terrenos irregulares.", "Peatones y otros equipos móviles.", "Visibilidad y maniobras.", "Señalización y zonas de exclusión."]),
    M("3", "Módulo 3: Carga y descarga", "Estabilidad durante el volquete", "La carga debe mantenerse estable y la descarga debe realizarse en un lugar seguro.", ["Carga uniforme y capacidad máxima.", "Riesgo de vuelco durante el volquete.", "Distancia a bordes y zanjas.", "Terreno firme durante la descarga."]),
    M("4", "Módulo 4: Revisión", "Mantenimiento y emergencias", "Las revisiones previas y el estacionamiento seguro son obligatorios en la práctica profesional.", ["Frenos, dirección, neumáticos y niveles.", "Alarmas y dispositivos de seguridad.", "Comunicación de averías.", "Estacionamiento y parada segura."]),
  ],
  retropala: [
    M("1", "Módulo 1: Retropala y pala cargadora", "Componentes e implementos", "Conoce la máquina mixta, sus implementos y sus aplicaciones.", ["Cazo frontal y brazo retro.", "Estabilizadores y controles.", "Implementos y acoplamientos.", "Capacidad y limitaciones."]),
    M("2", "Módulo 2: Excavación segura", "Terreno, servicios y estabilidad", "Antes de excavar hay que conocer el terreno y los posibles servicios enterrados.", ["Inspección del terreno.", "Taludes, zanjas y riesgo de desprendimiento.", "Servicios enterrados y señalización.", "Estabilidad de la máquina."]),
    M("3", "Módulo 3: Carga y movimiento", "Pala, giro y transporte", "Realiza movimientos suaves manteniendo control del implemento y del entorno.", ["Carga de materiales.", "Giro con implementos y zona de seguridad.", "Transporte de materiales.", "Peatones y señalista."]),
    M("4", "Módulo 4: Revisión", "Mantenimiento y estacionamiento", "La inspección diaria evita fallos y accidentes.", ["Hidráulica, neumáticos, frenos y niveles.", "Pasadores y acoplamientos.", "Detección de fugas y anomalías.", "Estacionamiento con implementos apoyados."]),
  ],
  telescopica: [
    M("1", "Módulo 1: Manipuladora telescópica", "Equipo e implementos", "Conoce el brazo telescópico, sus implementos y la información de capacidad.", ["Brazo telescópico y horquillas.", "Cazos y otros implementos.", "Tabla de cargas y alcance.", "Mandos y sistemas de seguridad."]),
    M("2", "Módulo 2: Estabilidad", "Carga, alcance y terreno", "La capacidad cambia con el alcance y la configuración del equipo.", ["Centro de gravedad y estabilidad.", "Carga máxima según alcance.", "Terreno y pendientes.", "Estabilizadores cuando proceda."]),
    M("3", "Módulo 3: Manejo", "Carga, descarga y circulación", "Planifica cada maniobra teniendo en cuenta visibilidad y entorno.", ["Recogida de palets y materiales.", "Transporte con carga baja y estable.", "Circulación en obra.", "Trabajo cerca de personas y obstáculos."]),
    M("4", "Módulo 4: Revisión", "Mantenimiento y emergencias", "La inspección y el mantenimiento son parte esencial de la operación.", ["Neumáticos, hidráulica, frenos y dirección.", "Implementos y acoplamientos.", "Averías y parada segura.", "Actuación ante pérdida de estabilidad."]),
  ],
  "prl-almacen": [
    M("1", "Módulo 1: Riesgos del almacén", "Identificación y prevención", "Aprende a reconocer los riesgos más frecuentes en almacenes y centros logísticos.", ["Caídas al mismo nivel y golpes.", "Atropellos y circulación de equipos.", "Caída de objetos y estanterías.", "Orden y limpieza."]),
    M("2", "Módulo 2: Manipulación y almacenamiento", "Buenas prácticas", "La organización del almacén reduce incidentes y mejora el trabajo seguro.", ["Apilado y estabilidad.", "Pasillos y zonas de paso.", "Carga y descarga.", "Señalización y zonas restringidas."]),
    M("3", "Módulo 3: EPI y emergencias", "Protección del trabajador", "Conoce los EPI y las pautas de actuación ante emergencias.", ["Calzado, chaleco, guantes y protección adecuada al riesgo.", "Incendios y evacuación.", "Accidentes y comunicación.", "Primeras actuaciones sin asumir riesgos."]),
    M("4", "Módulo 4: Ergonomía", "Posturas y organización", "Una buena organización también previene sobreesfuerzos y trastornos musculoesqueléticos.", ["Posturas de trabajo.", "Empuje y transporte.", "Pausas y organización de tareas.", "Comunicación de riesgos."]),
  ],
  "manipulacion-cargas": [
    M("1", "Módulo 1: Riesgos ergonómicos", "Peso, postura y frecuencia", "Identifica los factores que aumentan el riesgo durante la manipulación manual.", ["Peso, distancia y frecuencia.", "Posturas forzadas.", "Giros y movimientos repetitivos.", "Características del entorno."]),
    M("2", "Módulo 2: Levantamiento", "Técnica segura", "Aprende una secuencia de levantamiento que reduzca el esfuerzo innecesario.", ["Planificar el movimiento.", "Acercar la carga al cuerpo.", "Flexión controlada de piernas.", "Evitar giros bruscos con carga."]),
    M("3", "Módulo 3: Transporte y trabajo en equipo", "Mover cargas con seguridad", "No todas las cargas deben levantarse individualmente.", ["Uso de ayudas mecánicas.", "Transporte y visibilidad.", "Coordinación entre trabajadores.", "Empuje frente a tracción cuando proceda."]),
    M("4", "Módulo 4: Prevención", "Organización y hábitos", "La prevención combina técnica, organización y adaptación de la tarea.", ["Evaluación del riesgo.", "Alternancia de tareas.", "Orden y accesibilidad.", "Comunicación de molestias y riesgos."]),
  ],
  "gestion-almacen": [
    M("1", "Módulo 1: Organización del almacén", "Zonas y flujo de materiales", "Conoce cómo organizar espacios y recorridos para trabajar con eficiencia y seguridad.", ["Recepción, almacenamiento y expedición.", "Pasillos y zonas de circulación.", "Ubicaciones y señalización.", "Flujo de mercancías."]),
    M("2", "Módulo 2: Stock e inventario", "Control de existencias", "Aprende los principios básicos del control de stock.", ["Entradas y salidas.", "Inventario y recuento.", "Rotación y trazabilidad.", "Diferencias y ajustes."]),
    M("3", "Módulo 3: Preparación de pedidos", "Picking y expedición", "Una preparación ordenada reduce errores y riesgos.", ["Picking y ubicación.", "Comprobación de referencias y cantidades.", "Embalaje y etiquetado.", "Expedición y documentación."]),
    M("4", "Módulo 4: Seguridad logística", "Equipos, cargas y prevención", "La gestión del almacén debe integrar la seguridad de personas y mercancías.", ["Circulación de carretillas y peatones.", "Estabilidad de cargas y estanterías.", "PRL y EPI.", "Incidencias, daños y comunicación."]),
  ],
};

export function getCourse(id: string): Course | undefined { return courses.find((c) => c.id === id); }
export function getTemario(course: Course): Module[] { return temarios[course.id] ?? []; }

export const courses: Course[] = [
  { id: "carretillero", title: "Operario de Carretillas Elevadoras, Frontales y Retráctiles", description: "Aprende a manejar la carretilla elevadora con seguridad: estabilidad, carga y circulación.", category: "Manutención y Carretillas", image: "/cursos/carretilla-elevadora.png" },
  { id: "pemp", title: "Curso de Plataformas Elevadoras Móviles (PEMP)", description: "Trabajo en altura seguro con plataformas de tijera y de brazo articulado.", category: "Elevación y Plataformas", image: "/cursos/pemp.png" },
  { id: "puente-grua", title: "Curso de Puente Grúa y Polipasto", description: "Operación de puentes grúa y polipastos: eslingado, señalización y maniobras.", category: "Grúas y Equipos de Elevación", image: "/cursos/puente-grua.png" },
  { id: "transpaleta", title: "Curso de Transpaleta Manual y Eléctrica", description: "Uso correcto de transpaletas manuales y eléctricas en almacén y logística.", category: "Manutención y Carretillas", image: "/cursos/transpaleta.png" },
  { id: "apilador", title: "Curso de Apilador Eléctrico", description: "Manejo del apilador eléctrico para estibar y desestibar en estanterías.", category: "Manutención y Carretillas", image: "/cursos/apilador.png" },
  { id: "camion-pluma", title: "Curso de Camión Pluma / Grúa Autocargable", description: "Grúa autocargable sobre camión: cargas, estabilizadores y seguridad.", category: "Grúas y Equipos de Elevación", image: "/cursos/camion-pluma.png" },
  { id: "dumper", title: "Curso de Dúmper y Movimiento de Tierras", description: "Conducción de dúmper y fundamentos del movimiento de tierras en obra.", category: "Maquinaria y Movimiento de Tierras", image: "/cursos/dumper.png" },
  { id: "retropala", title: "Curso de Retropala y Pala Cargadora", description: "Manejo de retroexcavadora mixta y pala cargadora: excavación y carga.", category: "Maquinaria y Movimiento de Tierras", image: "/cursos/retropala.png" },
  { id: "telescopica", title: "Curso de Carretilla Telescópica (Manitou)", description: "Operación de la manipuladora telescópica en obra y logística agrícola.", category: "Manutención y Carretillas", image: "/cursos/telescopica.png" },
  { id: "prl-almacen", title: "Curso de Prevención de Riesgos Laborales (PRL) en Almacén", description: "Prevención de riesgos y buenas prácticas de seguridad en el almacén.", category: "Prevención de Riesgos Laborales", image: "/cursos/prl-almacen.png" },
  { id: "manipulacion-cargas", title: "Curso de Manipulación Manual de Cargas", description: "Técnicas de levantamiento y posturas seguras para evitar lesiones.", category: "Manipulación y Seguridad", image: "/cursos/manipulacion-cargas.png" },
  { id: "gestion-almacen", title: "Curso de Gestión de Almacén y Stock", description: "Organización del almacén, control de stock e inventario eficiente.", category: "Logística y Almacén", image: "/cursos/gestion-almacen.png" },
];
